### ISSUE TITLE
run script/prepare_lrw1000.py ,no file generated in the folder LRW1000_Public_pkl_jpeg

### ISSUE THREAD

**Issue by sodapeter** [Fengdalu/learn-an-effective-lip-reading-model-without-pains#10]
After run script/prepare_lrw1000.py, generated LRW1000_Public_pkl_jpeg folder , and trn ,tst ,val folder in it.

but nothing in these folders.

**Comment by Ritian-Li** [comment]
I met the same problem, did u solve it?

**Comment by Fengdalu** [comment]
`script/prepare_lrw1000.py` checks all video and audio files. That means you may need to unzip the downloaded dataset properly (audios and videos).

**Comment by Fengdalu** [comment]
see issue #11
