### ISSUE TITLE
将LRW-1000中的音频文件转化为预处理所需的npy格式

### ISSUE THREAD

**Issue by Ritian-Li** [Fengdalu/learn-an-effective-lip-reading-model-without-pains#11]
你好，请问将LRW-1000上的音频文件转化为预处理所需的npy格式，有什么需要注意的吗，还是仅仅读取然后保存就可以了吗？
另外，代码中的 border 是做什么的呢？
十分感谢！

**Comment by Fengdalu** [comment]
1. We only provided code of image processing in this repo. For audio files, you may need to check README of LRW1000 dataset to make it work properly.
2. `border` is the indicated variable for the word location in word-level lip reading. It is a list of the binary numbers.

**Comment by Katerina0815** [comment]
Hi! The audio file in lrw-1000 is .wav format. Does that mean we need to convert wav to npy before we run prepare_lrw1000.py? Thank you!
