### ISSUE TITLE
questions about testing on my own data

### ISSUE THREAD

**Issue by zt1112** [Fengdalu/learn-an-effective-lip-reading-model-without-pains#14]
Hi, I am very interested in the work of your team, and I have a few questions
1. On LRW1000, you need to choose 40 frames for a word, so do I need to adjust it according to the speech rate when testing on other videos?
2. The accuracy rate is very low when testing my own video, But the demo displayed on the team's homepage have good performance(such as https://vipl.ict.ac.cn/team.php?id=10) ，is the model here trained on LRW-1000?  or is there a private data set?
Looking forward to your reply！

**Comment by Fengdalu** [comment]
1. Sure. Besides, padding video frames outside the target work may provide more context information for recognition.
2. Yes.

**Comment by zt1112** [comment]
> * Sure. Besides, padding video frames outside the target work may provide more context information for recognition.
> * Yes.

Thanks for your quick reply!
So are you training on a private data set? I found that there is no "dao hang" label in LRW1000.

**Comment by Fengdalu** [comment]
> > * Sure. Besides, padding video frames outside the target work may provide more context information for recognition.
> > * Yes.
> 
> Thanks for your quick reply!
> So are you training on a private data set? I found that there is no "dao hang" label in LRW1000.

For more detailed information, please contact lipreading@vipl.ict.ac.cn or shuang.yang@ict.ac.cn .

**Comment by Fengdalu** [comment]
For Issues besides this repo or LRW-1000 datasets, please contact lipreading@vipl.ict.ac.cn or shuang.yang@ict.ac.cn .
