### ISSUE TITLE
Preview message

### ISSUE THREAD

**Issue by KunalShivhare** [Fengdalu/learn-an-effective-lip-reading-model-without-pains#15]
After testing for one video it is only showing the accuracy how to see the predicted word

**Comment by Fengdalu** [comment]
Sorry for the late reply.

You can modify the following lines to get the prediction of each video:

https://github.com/Fengdalu/learn-an-effective-lip-reading-model-without-pains/blob/9a1922c85c24acaa9be96c5dd99605aae46c421d/main_visual.py#L146

**Comment by KunalShivhare** [comment]
Thank You for helping me out
