### ISSUE TITLE
RuntimeError: [enforce fail at inline_container.cc:144] . PytorchStreamReader failed reading zip archive: failed finding central directory

### ISSUE THREAD

**Issue by woshihaozhu** [Fengdalu/learn-an-effective-lip-reading-model-without-pains#2]
`Traceback (most recent call last):
  File "main_visual.py", line 100, in <module>
    weight = torch.load(args.weights, map_location=torch.device('cpu'))
  File "/home/xjw/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/serialization.py", line 577, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/home/xjw/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/serialization.py", line 241, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: [enforce fail at inline_container.cc:144] . PytorchStreamReader failed reading zip archive: failed finding central directory`

I try to test lrw1000 model which downloaded from your google drive, but when i get ready eveything, some problems have raisen in test code, i guess the model couldn't load by using torch.load, so could you give some advise for the problem, thank you! 

`if (args.weights is not None):
    print('load weights')
    weight = torch.load(args.weights, map_location=torch.device('cpu'))
    load_mi`

**Comment by Fengdalu** [comment]
Please note the newly updated version (including weights links), thanks.
