### ISSUE TITLE
LRW-1000 Dataset cannot be valid anymore?

### ISSUE THREAD

**Issue by sd707589** [Fengdalu/learn-an-effective-lip-reading-model-without-pains#21]
Hi, 
The [LRW-1000](https://vipl.ict.ac.cn/view_database.php?id=14) seems invalid.

Could you keep it open please?

**Comment by Fengdalu** [comment]
Please email lipreading@vipl.ict.ac.cn for further information

**Comment by John-Yao** [comment]
@Fengdalu, Hi,  I email  lipreading@vipl.ict.ac.cn , dalu.feng@vipl.ict.ac.cn and  fengdalu@gmail.com but I cannot receive any feedback!
