### ISSUE TITLE
Where can I find the code that places the target word in the middle of the frames?

### ISSUE THREAD

**Issue by Leebh-kor** [Fengdalu/learn-an-effective-lip-reading-model-without-pains#23]
Hi

As introduced in the paper, I confirmed codes that the frame is fixed to 40 for each word in the scripts/prepare_lrw1000.py. 

However, it was not confirmed that the target word was placed in the middle of the frames.

Do you know where I can find the codes for this?

**Comment by Fengdalu** [comment]
Provided in the released files in LRW-1000 datasets. For application of LRW-1000, see: https://github.com/VIPL-Audio-Visual-Speech-Understanding/AVSU-VIPL#lrw-1000-a-naturally-distributed-large-scale-benchmark-for-lip-reading-in-the-wild-fg-2019
