### ISSUE TITLE
incorrect results: am i doing something wrong?

### ISSUE THREAD

**Issue by maylad31** [Fengdalu/learn-an-effective-lip-reading-model-without-pains#4]
Hi,
I tried to test it on some videos. i crop the lip region using dlib. I get results but the words do not match. What could possibly be wrong? Do you need videos at a specific fps? Please help. Thanks for the code!

**Comment by Fengdalu** [comment]
Hi, Thanks for your interest. This project is train and test on LRW/LRW1000 Dataset by using a fixed lip region. That means testing on other videos may not get accurate results.
