### ISSUE TITLE
word boundary?

### ISSUE THREAD

**Issue by hegc** [Fengdalu/learn-an-effective-lip-reading-model-without-pains#6]
Hi, when test samples of real videos(not in dataset), how to get "word boundary"?

**Comment by Fengdalu** [comment]
In LRW/LRW1000 dataset, the word boundary is provided by annotation files.

**Comment by hegc** [comment]
How to get word boundaries in actual use？

**Comment by hegc** [comment]
Word boundaries use the information of audio speech recognition, which is contrary to the original intention of lip recognition.

**Comment by Fengdalu** [comment]
> How to get word boundaries in actual use？

The Word Boundary can be obtained by Visual Voice Activity Detection in real-world applications.

**Comment by Norrrrrrr-lyn** [comment]
can we get the word boundary through the model provided? or is the model just for detecting certain words in the sentence?
