### ISSUE TITLE
Audio data format in LRW1000？

### ISSUE THREAD

**Issue by Zhuyanbin1023** [Fengdalu/learn-an-effective-lip-reading-model-without-pains#7]
Hi, I would like to ask the data format of the audio in the LRW1000 dataset is .wav, while the data format of prepare_lrw1000 is .npy, How to convert？

**Comment by Fengdalu** [comment]
The audio files can be read in python and convert into .npy format. You may need to modify `perpare_lrw1000.py` properly.

**Comment by Ritian-Li** [comment]
> Hi, I would like to ask the data format of the audio in the LRW1000 dataset is .wav, while the data format of prepare_lrw1000 is .npy, How to convert？

Hi, have you converted it and plz tell me how to do.

**Comment by Zhuyanbin1023** [comment]
Sorry，I haven't convert it successful------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年4月24日(星期六) 下午3:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Fengdalu/learn-an-effective-lip-reading-model-without-pains] Audio data format in LRW1000？ (#7)
