### ISSUE TITLE
RuntimeWarning: invalid value encountered in double_scalars

### ISSUE THREAD

**Issue by PatrickPrakash** [Fengdalu/learn-an-effective-lip-reading-model-without-pains#9]
Hey there, I tried to run your program and get this warning. Can you help me out. I'm just starting deeplearning 😊

```
load weights
loaded params/tot params:151/151
miss matched params: []
Start Testing, Data Length: 0
start testing
main_visual.py:155: RuntimeWarning: Mean of empty slice.
  acc = float(np.array(v_acc).reshape(-1).mean())
/home/ubuntu/anaconda3/envs/learn_lip/lib/python3.8/site-packages/numpy/core/_methods.py:188: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
acc=nan
```

**Comment by Fengdalu** [comment]
The program prints `Start Testing, Data Length: 0`, which means it does not read any testing data. You may specific data path to read data properly.

**Comment by PatrickPrakash** [comment]
I didn't find any dataset path specific argument in main python file. I link the lrw dataset to the root as per documentation and run the argument as per documentation. Can you please help me out how can I specify the test dataset?Thanks

**Comment by Fengdalu** [comment]
Can you find `lrw_roi_80_116_175_211_npy_gray_pkl_jpeg` in your project folder after run `scripts/prepare_lrw.py` ?

**Comment by PatrickPrakash** [comment]
Yeah , I saw that

**Comment by PatrickPrakash** [comment]
But nothing is inside the folder

**Comment by PatrickPrakash** [comment]
The issue was solved by changing the name of dataset which was "lrw_mp4" but actually was "lipread_mp4". It will be great if you could share your social media handle or email so that i can contact you for further questions.

**Comment by Fengdalu** [comment]
You can contact me via fengdalu@gmail.com or dalu.feng@vipl.ict.ac.cn. Moreover, sharing your problem in Github issues is recommended for further disscutions.
